apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: prod-ns
  labels:
    app: java-app
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
      env: prod
  template:
    metadata:
      labels:
        app: java-app
        env: prod
    spec:
      containers:
      - name: java-app
        image: rhxpchispi/zlab-java-app:prod-latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WELCOME_MESSAGE
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VERSION
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_URL
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_COLOR
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: prod-ns
spec:
  selector:
    app: java-app
    env: prod
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 8080
  type: ClusterIP