apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: test-ns
  labels:
    app: java-app
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
      env: test
  template:
    metadata:
      labels:
        app: java-app
        env: test
    spec:
      containers:
      - name: java-app
        image: rhxpchispi/zlab-java-app:test-latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WELCOME_MESSAGE
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VERSION
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_URL
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_COLOR
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: test-ns
spec:
  selector:
    app: java-app
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
  type: NodePort